# coding: utf-8

"""
    Robolytix

    Robolytix is the key online analytic and monitoring tool for Robotic Process Automation using Sonar technology to evaluate, audit, monitor and improve performance of robots operating in any application, RPA platform or custom solution. Manage your RPA projects effectively with exact KPIs. Visualise your whole process at one place.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.inline_response_default2 import InlineResponseDefault2  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponseDefault2(unittest.TestCase):
    """InlineResponseDefault2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponseDefault2(self):
        """Test InlineResponseDefault2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_default2.InlineResponseDefault2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
