# coding: utf-8

"""
    Robolytix

    Robolytix is the key online analytic and monitoring tool for Robotic Process Automation using Sonar technology to evaluate, audit, monitor and improve performance of robots operating in any application, RPA platform or custom solution. Manage your RPA projects effectively with exact KPIs. Visualise your whole process at one place.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_listprocesses(self):
        """Test case for listprocesses

        List processes  # noqa: E501
        """
        pass

    def test_listtypes(self):
        """Test case for listtypes

        List types  # noqa: E501
        """
        pass

    def test_sonar(self):
        """Test case for sonar

        Sonar  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
