# coding: utf-8

# flake8: noqa
"""
    Robolytix

    Robolytix is the key online analytic and monitoring tool for Robotic Process Automation using Sonar technology to evaluate, audit, monitor and improve performance of robots operating in any application, RPA platform or custom solution. Manage your RPA projects effectively with exact KPIs. Visualise your whole process at one place.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.inline_response_default import InlineResponseDefault
from swagger_client.models.inline_response_default1 import InlineResponseDefault1
from swagger_client.models.inline_response_default2 import InlineResponseDefault2
from swagger_client.models.inline_response_default2_data import InlineResponseDefault2Data
from swagger_client.models.message import Message
from swagger_client.models.process import Process
from swagger_client.models.type import Type
